### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by chandnikathuria1992** [masoudnick/Brain-Tumor-MRI-Classification#10]
Please provide details about dataset. From where these images have been taken?
Thanks

**Comment by masoudnick** [comment]
Hi @chandnikathuria1992,
This dataset is a combination of the following two datasets :
[figshare](https://figshare.com/articles/dataset/brain_tumor_dataset/1512427)
[kaggle](https://www.kaggle.com/sartajbhuvaji/brain-tumor-classification-mri/metadata)
I think kaggle dataset has a problem that the Glioma class images are not categorized correctly, I realized this from the results of other people's work as well as the different models I trained, which is why I deleted the images in this folder and used the images on the figshare site instead. Of course, I may have made a mistake in this case.

**Comment by chandnikathuria1992** [comment]
Kaggle dataset contains 3024 images in total. So how many images have you
taken from figshare, as your dataset contains 7022 images. Please share
details as I want to test my model for research. Also figshare data is in a
different format. Can you please guide me how or from where you have got
the JPG format. It would be great help if you can provide details.

**Comment by masoudnick** [comment]
Yes, sure
The number of images of figshare is 3064 not kaggle, and because this dataset has no images for notumor class, I used the images of the no class this dataset, If I'm not wrong. [link](https://www.kaggle.com/ahmedhamada0/brain-tumor-detection)
I remembered this when you asked this question :grimacing:
And figshare dataset is organized in matlab data format, You can use this code for extracting data from .mat to .jpg. [link](https://github.com/masoudnick/Brain-Tumor-MRI-Classification/blob/main/fighare-image-extractor.py)
